apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: blog-nginx
  # put your Azure public IP in here
  #loadBalancerIP: a.b.c.d
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: blog-nginx
    spec:
      containers:
      - name: nginx
        image: flexlab/my-fake-blog:nginx-20180407
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      imagePullSecrets:
      - name: dockerhubkey
